#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "94b3d3d30ec0470b8644f36e124d7b26" }
]

[assets]
directory = "./public"
